import '../../public/style/globals.css';
import localFont from 'next/font/local';
 
const primaryFont = localFont({ src: '../../public/assets/fonts/made-tommy-soft.otf', variable: '--font-primary' });

export const metadata = {
  title: 'SSBU Stage Picker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="./favicon-32x32.png"
        type="image/png"
        sizes="any"
      />
      <body className={primaryFont.variable}>{children}</body>
    </html>
  )
}
